export type HexTile = {
  terrain: string;
  label?: string;
  rotate?: 0 | 1 | 2 | 3 | 4 | 5;
};

export const hexData: HexTile[][] = [
  [
    { terrain: "town", label: "Ogon" },
    { terrain: "river-1", rotate: 2 },
    { terrain: "countryside" },
    { terrain: "mountains" },
    { terrain: "countryside" },
    { terrain: "hills" },
    { terrain: "desert" },
    { terrain: "hills" },
    { terrain: "countryside" },
    { terrain: "town", label: "Anglae" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "swamp" },
    { terrain: "swamp" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
  ],
  [
    { terrain: "mountains" },
    { terrain: "river-1", rotate: 2 },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "hills" },
    { terrain: "hills" },
    { terrain: "desert-ruins", label: "Ruins" },
    { terrain: "road-1" },
    { terrain: "road-2", rotate: 4 },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "swamp" },
    { terrain: "swamp" },
    { terrain: "forest" },
    { terrain: "town", label: "Galden" },
    { terrain: "farmland" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "farmland" },
    { terrain: "forest" },
  ],
  [
    { terrain: "mountains" },
    { terrain: "forest" },
    { terrain: "river-2", rotate: 5 },
    { terrain: "forest" },
    { terrain: "mountains" },
    { terrain: "countryside" },
    { terrain: "desert" },
    { terrain: "hills" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "swamp" },
    { terrain: "swamp" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "farmland-road-2", rotate: 3 },
    { terrain: "road-1" },
    { terrain: "farmland-road-2" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "farmland-road-2", rotate: 1 },
    { terrain: "castle", label: "Drogat" },
    { terrain: "farmland" },
  ],
  [
    { terrain: "forest" },
    { terrain: "river-2", rotate: 2 },
    { terrain: "forest" },
    { terrain: "mountains" },
    { terrain: "mountains" },
    { terrain: "mountains" },
    { terrain: "hills" },
    { terrain: "desert" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "swamp" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "farmland" },
    { terrain: "town", label: "Halowich" },
    { terrain: "farmland-road-1" },
    { terrain: "forest-road-2", rotate: 4 },
    { terrain: "farmland" },
    { terrain: "farmland" },
  ],
  [
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "river-2", rotate: 5 },
    { terrain: "mountains" },
    { terrain: "mountains" },
    { terrain: "forest" },
    { terrain: "hills" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "swamp" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "farmland" },
    { terrain: "road-2", rotate: 5 },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
  ],
  [
    { terrain: "countryside" },
    { terrain: "river-1", rotate: 1 },
    { terrain: "countryside" },
    { terrain: "mountains" },
    { terrain: "countryside" },
    { terrain: "hills" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "swamp" },
    { terrain: "forest" },
    { terrain: "swamp" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "farmland" },
    { terrain: "farmland-road-2", rotate: 4 },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
  ],
  [
    { terrain: "countryside" },
    { terrain: "river-2", rotate: 2 },
    { terrain: "countryside" },
    { terrain: "mountains" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "swamp" },
    { terrain: "forest-temple", label: "Branwyn" },
    { terrain: "forest" },
    { terrain: "swamp" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "town", label: "Brigud" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
  ],
  [
    { terrain: "hills" },
    { terrain: "river-2", rotate: 5 },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "mountains" },
    { terrain: "forest" },
    { terrain: "hills" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "forest" },
    { terrain: "farmland-road-2", rotate: 3 },
    { terrain: "road-1" },
    { terrain: "road-2", rotate: 4 },
    { terrain: "road-2", rotate: 3 },
    { terrain: "road-2" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
  ],
  [
    { terrain: "mountains-ruins", label: "Jakor" },
    { terrain: "river-2", rotate: 2 },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "hills" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "hills" },
    { terrain: "forest" },
    { terrain: "swamp" },
    { terrain: "forest" },
    { terrain: "town", label: "Erwyn" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "road-1", rotate: 5 },
    { terrain: "hills" },
    { terrain: "hills" },
    { terrain: "countryside" },
  ],
  [
    { terrain: "hills" },
    { terrain: "river-2", rotate: 5 },
    { terrain: "forest" },
    { terrain: "hills" },
    { terrain: "town", label: "Cumry" },
    { terrain: "countryside" },
    { terrain: "mountains" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "town", label: "Cawther" },
    { terrain: "hills" },
    { terrain: "hills" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "swamp" },
    { terrain: "swamp" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "hills" },
    { terrain: "mountains" },
    { terrain: "temple-1", label: "Sulwyth", rotate: 5 },
    { terrain: "mountains" },
    { terrain: "hills" },
  ],
  [
    { terrain: "hills" },
    { terrain: "river-2", rotate: 2 },
    { terrain: "hills" },
    { terrain: "swamp" },
    { terrain: "countryside" },
    { terrain: "mountains" },
    { terrain: "mountains" },
    { terrain: "hills" },
    { terrain: "hills" },
    { terrain: "hills" },
    { terrain: "countryside" },
    { terrain: "mountains" },
    { terrain: "hills" },
    { terrain: "hills" },
    { terrain: "mountains" },
    { terrain: "countryside" },
    { terrain: "countryside" },
    { terrain: "forest" },
    { terrain: "countryside" },
    { terrain: "swamp" },
    { terrain: "forest" },
    { terrain: "mountains" },
    { terrain: "mountains" },
    { terrain: "mountains" },
    { terrain: "mountains" },
  ],
];
